#!/usr/bin/env bash

TRAVIS_BUILD_DIR=${TRAVIS_BUILD_DIR:-$(pwd)}

DRUPAL_TRAVIS_PROJECT_BASEDIR=${DRUPAL_TRAVIS_PROJECT_BASEDIR:-${TRAVIS_BUILD_DIR}}

DRUPAL_TRAVIS_DISTRIBUTION=${DRUPAL_TRAVIS_DISTRIBUTION:-drupal}

DRUPAL_TRAVIS_COMPOSER_NAME=${DRUPAL_TRAVIS_COMPOSER_NAME:-$(jq -r .name ${DRUPAL_TRAVIS_PROJECT_BASEDIR}/composer.json)}

DRUPAL_TRAVIS_PROJECT_NAME=${DRUPAL_TRAVIS_PROJECT_NAME-$(echo ${DRUPAL_TRAVIS_COMPOSER_NAME} | cut -d '/' -f 2)}

DRUPAL_TRAVIS_TEST_JAVASCRIPT=${DRUPAL_TRAVIS_TEST_JAVASCRIPT:-1}

DRUPAL_TRAVIS_TEST_PHP=${DRUPAL_TRAVIS_TEST_PHP:-1}

DRUPAL_TRAVIS_DRUPAL_VERSION=${DRUPAL_TRAVIS_DRUPAL_VERSION:-^8.6}

# The version of thunder to test against, as long as drupal 8.6.0 is not released, only the 8.x-3.x dev branch is supported
DRUPAL_TRAVIS_THUNDER_VERSION=${DRUPAL_TRAVIS_THUNDER_VERSION:-dev-8.x-3.x}

DRUPAL_TRAVIS_TEST_BASE_DIRECTORY=${DRUPAL_TRAVIS_TEST_BASE_DIRECTORY:-/tmp/test/${DRUPAL_TRAVIS_PROJECT_NAME}}

# The directory, where drupal will be installed, defaults to ${DRUPAL_TRAVIS_TEST_BASE_DIRECTORY}/install
DRUPAL_TRAVIS_DRUPAL_INSTALLATION_DIRECTORY=${DRUPAL_TRAVIS_DRUPAL_INSTALLATION_DIRECTORY:-${DRUPAL_TRAVIS_TEST_BASE_DIRECTORY}/install}

DRUPAL_TRAVIS_TEST_GROUP=${DRUPAL_TRAVIS_TEST_GROUP-${DRUPAL_TRAVIS_PROJECT_NAME}}

DRUPAL_TRAVIS_TEST_CODING_STYLES=${DRUPAL_TRAVIS_TEST_CODING_STYLES:-1}

DRUPAL_TRAVIS_HOST=${DRUPAL_TRAVIS_HOST:-127.0.0.1}

DRUPAL_TRAVIS_HTTP_PORT=${DRUPAL_TRAVIS_HTTP_PORT:-8888}

DRUPAL_TRAVIS_SELENIUM_CHROME_VERSION=${DRUPAL_TRAVIS_SELENIUM_CHROME_VERSION:-latest}

DRUPAL_TRAVIS_SELENIUM_HOST=${DRUPAL_TRAVIS_SELENIUM_HOST:-${DRUPAL_TRAVIS_HOST}}

DRUPAL_TRAVIS_SELENIUM_PORT=${DRUPAL_TRAVIS_SELENIUM_PORT:-4444}

DRUPAL_TRAVIS_DATABASE_HOST=${DRUPAL_TRAVIS_DATABASE_HOST:-${DRUPAL_TRAVIS_HOST}}

DRUPAL_TRAVIS_DATABASE_PORT=${DRUPAL_TRAVIS_DATABASE_PORT:-3306}

DRUPAL_TRAVIS_DATABASE_USER=${DRUPAL_TRAVIS_DATABASE_USER:-travis}

# The mysql password for user ${DRUPAL_TRAVIS_DATABASE_USER}, empty by default.
DRUPAL_TRAVIS_DATABASE_PASSWORD=${DRUPAL_TRAVIS_DATABASE_PASSWORD}

DRUPAL_TRAVIS_DATABASE_NAME=${DRUPAL_TRAVIS_DATABASE_NAME:-drupaltesting}

DRUPAL_TRAVIS_TEST_RUNNER=${DRUPAL_TRAVIS_TEST_RUNNER:-phpunit}

DRUPAL_TRAVIS_LOCK_FILES_DIRECTORY=${DRUPAL_TRAVIS_LOCK_FILES_DIRECTORY:-${DRUPAL_TRAVIS_TEST_BASE_DIRECTORY}/finished-stages}

DRUPAL_TRAVIS_NO_CLEANUP=${DRUPAL_TRAVIS_NO_CLEANUP}

export SYMFONY_DEPRECATIONS_HELPER=${SYMFONY_DEPRECATIONS_HELPER-weak}

export SIMPLETEST_BASE_URL=${SIMPLETEST_BASE_URL:-http://${DRUPAL_TRAVIS_HOST}:${DRUPAL_TRAVIS_HTTP_PORT}}

export SIMPLETEST_DB=${SIMPLETEST_DB:-mysql://${DRUPAL_TRAVIS_DATABASE_USER}:${DRUPAL_TRAVIS_DATABASE_PASSWORD}@${DRUPAL_TRAVIS_DATABASE_HOST}:${DRUPAL_TRAVIS_DATABASE_PORT}/${DRUPAL_TRAVIS_DATABASE_NAME}}

export MINK_DRIVER_ARGS_WEBDRIVER=${MINK_DRIVER_ARGS_WEBDRIVER-"[\"chrome\", null, \"http://${DRUPAL_TRAVIS_SELENIUM_HOST}:${DRUPAL_TRAVIS_SELENIUM_PORT}/wd/hub\"]"}
