#!/usr/bin/env bash

TRAVIS_BUILD_DIR=${TRAVIS_BUILD_DIR:-.}

THUNDER_TRAVIS_PROJECT_BASEDIR=${THUNDER_TRAVIS_PROJECT_BASEDIR:-$TRAVIS_BUILD_DIR}

THUNDER_TRAVIS_TEST_JAVASCRIPT=${THUNDER_TRAVIS_TEST_JAVASCRIPT:-1}

THUNDER_TRAVIS_TEST_PHP=${THUNDER_TRAVIS_TEST_PHP:-1}

THUNDER_TRAVIS_DRUPAL_VERSION=${THUNDER_TRAVIS_DRUPAL_VERSION:-^8.6}

THUNDER_TRAVIS_THUNDER_VERSION=${THUNDER_TRAVIS_THUNDER_VERSION:-^8.2}

THUNDER_TRAVIS_DRUPAL_INSTALLATION_DIRECTORY=${THUNDER_TRAVIS_DRUPAL_INSTALLATION_DIRECTORY:-$THUNDER_TRAVIS_PROJECT_BASEDIR/../tt-drupal-installation}

THUNDER_TRAVIS_COMPOSER_NAME=${THUNDER_TRAVIS_COMPOSER_NAME:-`jq -r .name $THUNDER_TRAVIS_PROJECT_BASEDIR/composer.json`}

THUNDER_TRAVIS_TEST_GROUP=${THUNDER_TRAVIS_TEST_GROUP-$(echo ${THUNDER_TRAVIS_COMPOSER_NAME} | cut -d '/' -f 2)}

THUNDER_TRAVIS_SIMPLETEST_PORT=${THUNDER_TRAVIS_SIMPLETEST_PORT:-8888}

THUNDER_TRAVIS_SIMPLETEST_HOST=${THUNDER_TRAVIS_SIMPLETEST_HOST:-127.0.0.1}

THUNDER_TRAVIS_SELENIUM_CHROME_VERSION=${THUNDER_TRAVIS_SELENIUM_CHROME_VERSION:-latest}

export SYMFONY_DEPRECATIONS_HELPER=${SYMFONY_DEPRECATIONS_HELPER-weak}

export SIMPLETEST_BASE_URL=${SIMPLETEST_BASE_URL:-http://${THUNDER_TRAVIS_SIMPLETEST_HOST}:${THUNDER_TRAVIS_SIMPLETEST_PORT}}

export SIMPLETEST_DB=${SIMPLETEST_DB:-sqlite://localhost/sites/default/files/.sqlite}

export MINK_DRIVER_ARGS_WEBDRIVER=${MINK_DRIVER_ARGS_WEBDRIVER-'["chrome", null, "http://localhost:4444/wd/hub"]'}
